// global
export const IS_LOADING = "IS_LOADING";

// user
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_CLEAN = "USER_REGISTER_CLEAN";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_CLEAN = "USER_LOGIN_CLEAN";

export const USER_FORGET_PASSWORD = "USER_FORGET_PASSWORD";
export const USER_FORGET_PASSWORD_SUCCESS = "USER_FORGET_PASSWORD_SUCCESS";
export const USER_FORGET_PASSWORD_CLEAN = "USER_FORGET_PASSWORD_CLEAN";
